name: g_diffuser
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy 
  - pip:
    - pyyaml
    - opencv-python
    - aiofiles
    - transformers
    - discord
    - ftfy
    - twisted
    - hupper
    - wsgicors
    - service_identity
    - grpcio
    - google-api-python-client
    - scikit-image
    - git+https://github.com/huggingface/diffusers.git    