name: g_diffuser
channels:
  - pytorch
  - defaults
dependencies:
  - python
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy 
  - pip:
    - cv2
    - psutil
    - transformers
    - discord
    - ftfy
    - git+https://github.com/huggingface/diffusers    