- id: "stable-diffusion-v1-4"
  default: True
  enabled: True
  visible: True
  name: "Stable Diffusion V1.4"
  description: "Stable Diffusion using the CompVis model and our Unified pipeline"
  class: "UnifiedPipeline"
  model: ""
  local_model: "./stable-diffusion-v1-4"
  has_fp16: True
  use_auth_token: False
- id: "waifu-diffusion"
  enabled: False
  visible: True
  name: "Waifu Diffusion V1.3"
  description: "Stable Diffusion using the Hakurei Waifu Diffusion model and our Unified pipeline"
  class: "UnifiedPipeline"
  model: "hakurei/waifu-diffusion"
  local_model: "./waifu-diffusion"
  has_fp16: True
  use_auth_token: False